[package]
name = "vs-assets"
version = "0.1.0"
edition = "2021"

[dependencies]
"common" = { path = "../common" }
"bevy" = { version = "0.14"}
tiled = "0.12"
thiserror = "1.0"
serde_json = "1.0"
serde = "1.0"
rand = "0.8.5"