<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="tilesheet" tilewidth="32" tileheight="32" tilecount="1024" columns="32">
 <image source="textures/tilesheet.png" width="1024" height="1024"/>
 <tile id="0" type="grass_decorated"/>
 <tile id="1" type="grass_decorated"/>
 <tile id="2" type="grass_decorated"/>
 <tile id="3" type="grass_decorated"/>
 <tile id="4" type="grass_decorated"/>
 <tile id="5" type="grass_decorated"/>
 <tile id="6" type="grass_decorated"/>
 <tile id="7" type="grass_decorated"/>
 <tile id="32" type="grass_decorated"/>
 <tile id="33" type="grass_decorated"/>
 <tile id="34" type="grass_decorated"/>
 <tile id="35" type="grass_decorated"/>
 <tile id="36" type="grass_decorated"/>
 <tile id="37" type="grass_decorated"/>
 <tile id="38" type="grass_decorated"/>
 <tile id="39" type="grass_decorated"/>
 <tile id="64" type="grass_decorated"/>
 <tile id="65" type="grass_decorated"/>
 <tile id="66" type="grass_decorated"/>
 <tile id="67" type="grass_decorated"/>
 <tile id="68" type="grass_decorated"/>
 <tile id="69" type="grass_decorated"/>
 <tile id="70" type="grass_decorated"/>
 <tile id="71" type="grass_decorated"/>
 <tile id="96" type="grass_decorated"/>
 <tile id="97" type="grass_decorated"/>
 <tile id="98" type="grass_decorated"/>
 <tile id="99" type="grass_decorated"/>
 <tile id="100" type="grass_decorated"/>
 <tile id="101" type="grass_decorated"/>
 <tile id="102" type="grass_decorated"/>
 <tile id="103" type="grass_decorated"/>
 <tile id="128" type="grass_road"/>
 <tile id="129" type="grass_road"/>
 <tile id="130" type="grass_road_vertical_left"/>
 <tile id="131" type="grass_road_vertical_right"/>
 <tile id="132" type="grass_road_horizontal_top"/>
 <tile id="133" type="grass_road_horizontal_top"/>
 <tile id="134" type="grass_road_horizontal_top"/>
 <tile id="135" type="grass_road_horizontal_top"/>
 <tile id="160" type="grass_road"/>
 <tile id="161" type="grass_road"/>
 <tile id="162" type="grass_road_vertical_left"/>
 <tile id="163" type="grass_road_vertical_right"/>
 <tile id="164" type="grass_road_horizontal_bottom"/>
 <tile id="165" type="grass_road_horizontal_bottom"/>
 <tile id="166" type="grass_road_horizontal_bottom"/>
 <tile id="167" type="grass_road_horizontal_bottom"/>
 <tile id="192" type="grass_road"/>
 <tile id="193" type="grass_road"/>
 <tile id="194" type="grass_road_vertical_left"/>
 <tile id="195" type="grass_road_vertical_right"/>
 <tile id="230" type="grass_decorated"/>
 <tile id="231" type="grass_decorated"/>
</tileset>
